version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-ai-backend
    ports:
      - "8000:8000"
    networks:
      - ai_service_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: my-ai-frontend
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - ai_service_network

networks:
  ai_service_network:
    driver: bridge
